version: "3.7"
services:
  postgres:
    image: "postgres:15.1"
    restart: always
    volumes: 
      - ./.data:/var/lib/postgresql/data
      - ./migration:/migration
    env_file:
      - .env
    expose: ["5432"]
    ports: ["5432:5432"]
  api:
    image: "node:18"
    depends_on:
      - postgres
    restart: always
    working_dir: /app/api
    command: bash -c "npm i && npm run dev"
    volumes: 
      - ./api:/app/api
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - .env
    ports: ["8080:8080"]
  web:
    image: "node:19"
    depends_on:
      - api
    working_dir: /app/web
    command: bash -c "npm i && npm run dev"
    volumes: 
      - ./web:/app/web
    environment:
      CHOKIDAR_USEPOLLING: "true"
    expose: ["3000"]
    env_file:
      - ./web/.env
    ports: ["3000:3000"]
